export const studentsResult = [
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "kabir Sabbir",
		grade: "A+",
		percantage: "88%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Neamul Islam",
		grade: "A",
		percantage: "70%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "kabir Islam",
		grade: "A+",
		percantage: "80%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Sohel Rana",
		grade: "B",
		percantage: "60%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Tanvir kabir ",
		grade: "F",
		percantage: "30%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Md Faruk",
		grade: "c",
		percantage: "50%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "John Dady",
		grade: "B",
		percantage: "40%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Nazmul kabir",
		grade: "A+",
		percantage: "98%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Hasna Akter",
		grade: "A+",
		percantage: "90%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "One",
		name: "Azim Lingkon",
		grade: "F",
		percantage: "20%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Alexander kabir",
		grade: "A",
		percantage: "75%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Benjamin Ethan",
		grade: "A",
		percantage: "73%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Frederick Isaac",
		grade: "A+",
		percantage: "88%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "James Kevin",
		grade: "A+",
		percantage: "90%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Oliver Patrick",
		grade: "A",
		percantage: "71%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Robert Isaac",
		grade: "F",
		percantage: "22%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Bella kabir",
		grade: "B",
		percantage: "40%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Emily Fiona",
		grade: "B",
		percantage: "45%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Lily Olivia",
		grade: "A+",
		percantage: "88%",
	},
	{
		id: crypto.randomUUID(),
		classNumber: "Two",
		name: "Penelope Quinn",
		grade: "C",
		percantage: "55%",
	},
];
